version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-devops: 
    build:
      context: .
      args:                      #those are solely used by the build process 
        NODE_ENV: development    #colon is used
    volumes:
      - ./:/app                  #regular volume
      - /app/node_modules        #anonymous volume
    environment:                 #those are passed through the application 
      - NODE_ENV=development     #equal sign is used
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET} 

    command:
      npm run startdev
    
