version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      #not working directly mapping single file
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- type: bind
      #  source: ./nginx/default.conf
      #  target: /etc/nginx/conf.d/default.conf
      #  read_only: true
  node-devops:
    build: .           #because we build our own image
    #ports:                   #we have just installed nginx, all connnections go through it 
    #  - "3000-3001:3000"     #so no longer need node-devops open ports
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo       #not build because we take it directly from docker hub
    environment:
      - MONGO_INITDB_ROOT_USERNAME={MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD={MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis


volumes:
  mongo-db: